### PR TITLE
support CLANG32 system too

### PR DESCRIPTION
**Pull request by past-due**

### CODE REVIEW

**Comment by Biswa96** [comment]
Remember clang32 has only minimal toolchain (compiler, crt) packages, not every libraries.

**Comment by past-due** [comment]
> Remember clang32 has only minimal toolchain (compiler, crt) packages, not every libraries.

Yep, but fortunately that's all we need. :)

**Comment by jeremyd2019** [comment]
I have been thinking it may be about time to enable clang32 for more packages.

**Comment by Biswa96** [comment]
Wondering how many people are actually using 32bit OS for actual work. I know only one.

**Comment by jeremyd2019** [comment]
I don't know about actually using 32-bit OSes, but I've seen @revelator and @past-due now express interest in the clang32 toolchain

**Comment by past-due** [comment]
> I don't know about actually using 32-bit OSes, but I've seen @revelator and @past-due now express interest in the clang32 toolchain

Indeed, the toolchain is the particular area of interest (at least until there's a clang-cross environment 😎). Believe it or not, we still have folks who want 32-bit Windows binaries.

**Comment by lazka** [comment]
@past-due just to be sure: you are aware that our clang32 targets ucrt and is thus more or less win10 only?

**Comment by past-due** [comment]
> @past-due just to be sure: you are aware that our clang32 targets ucrt and is thus more or less win10 only?

I am aware of the UCRT targeting, however the UCRT is available for (and serviced by Windows Update on) versions of Windows prior to Windows 10 as well. (It's considered a Windows component, even on earlier versions of Windows. And there are several options to ensure it's installed.)

**Comment by mati865** [comment]
I hope that you are aware that there can be no support for `clang32` subsystem from MSYS2 because of address space constrains. Getting 32-bit LLVM 12 to build itself was already hard so we might have to drop it at any LLVM upgrade.

**Comment by past-due** [comment]
> I hope that you are aware that there can be no support for `clang32` subsystem from MSYS2 because of address space constrains. Getting 32-bit LLVM 12 to build itself was already hard so we might have to drop it at any LLVM upgrade.

Presumably this same concern would not apply to a `clang-cross` environment, as described in https://github.com/msys2/MINGW-packages/discussions/8736 and is being worked on in https://github.com/msys2/MINGW-packages/pull/8762?

Once that toolchain exists, it could theoretically be used to build the `clang32` packages?

**Comment by mati865** [comment]
> Once that toolchain exists, it could theoretically be used to build the clang32 packages?

That would probably require changing every PKGBUILD or inventing yet another subsystem.

**Comment by revelator** [comment]
most of the adress space restraints seem to be fixed if defaulting to large adress aware on 32 bit builds atleast im having no problems since i started using it :). UCRT is supported back to atleast vista though you have to install it manually, XP support might be a strecth though. Atm most problems are related to the clang tools not supporting the workarounds the gnu compilers have established to keep compatibility with windows builds, like version scripting etc. It would also be rather easy for a developer to just change the runtime from UCRT to MSVC if needed though they would have to do this themself.

**Comment by eine** [comment]
Thanks!

**Comment by past-due** [comment]
@eine Actually, despite CI passing, it does not appear to be downloading the `clang32.db`, and attempts to install `mingw-w64-clang-i686-*` packages fail. Hmm.

**Comment by lazka** [comment]
we didn't add any servers for it in pacman.conf

**Comment by past-due** [comment]
> we didn't add any servers for it in pacman.conf

Ah, looks like we need a `/etc/pacman.d/mirrorlist.clang32` as well.

**Pull request merged**
