### PR TITLE
Downgrade @actions/cache

### PR DESCRIPTION
**Pull request by lazka**
Due to https://github.com/actions/toolkit/issues/1311

### CODE REVIEW

**Comment by lazka** [comment]
released as 2.15.1

**Comment by jeremyd2019** [comment]
You don't have to keep this version frozen on my account: I believe the issue with it exporting MSYS2 env var was fixed, so it's just the issue on a self-hosted runner that doesn't have zstd.exe or gzip.exe on the PATH.  On my self-hosted runners, the setup-msys2 cache is more of an annoyance than a help anyway, so I would not be bothered by it not working.  If I really cared I could put a zstd on the PATH in my runner setup.

**Comment by lazka** [comment]
OK, thanks. I was wondering about that.

I'll update it then, so it's part of the next release in some weeks/months.

**Comment by lazka** [comment]
I've pushed a release with it now already. See https://github.com/msys2/msys2-autobuild/commit/79096b753cf3a620aa67fcb215bb17a7578ba813

**Pull request merged**
