### PR TITLE
README: Add fail-fast option in all matrix examples

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
Should there be an explanation why `fail-fast` is required or what it does?

**Comment by eine** [comment]
I don't think that fail-fast should be used in the readme. That's specific about how GitHub Actions handles matrices; unrelated to MSYS2 itself. Many users might want the default fail-fast behaviour indeed.

However, I agree it would be interesting to add a comment with a reference to the corresponding page in GitHub's docs, and a brief explanation of why using it might be desirable.

**Comment by Biswa96** [comment]
Thanks for the review. I have added a comment with a reference to the corresponding page in GitHub's docs.

**Review by eine — APPROVED** [review]
LGTM!

**Comment by eine** [comment]
Thanks!

**Pull request merged**
