### PR TITLE
New base: 2021-02-13

### PR DESCRIPTION
**Pull request by lazka**
https://github.com/msys2/msys2-installer/releases/tag/2021-02-13

### CODE REVIEW

**Comment by lazka** [comment]
something isn't working, needs investigating..

**Comment by Biswa96** [comment]
>  error: mingw64: signature is marginal trust

1. https://archived.forum.manjaro.org/t/issues-with-signature-is-marginal-trust-or-invalid-or-corrupted-package/33268/5
2. https://forum.endeavouros.com/t/faq-issues-with-signature-is-marginal-trust-or-invalid-or-corrupted-package/6756
3. https://bbs.archlinux.org/viewtopic.php?id=233480

**Comment by lazka** [comment]
yeah, we disabled `pacman-key --refresh-keys` to speed things up and assumed keys in the installer would not be expired.

**Comment by lazka** [comment]
I've pulled the release -> next steps here https://github.com/msys2/MSYS2-keyring/pull/6

**Pull request closed without merging**
