### PR TITLE
cache: conditionally disable the install cache, unset by default

### LINKED ISSUE #61: Lost files in the cache
I managed to get a file lost in our cache here: https://github.com/msys2/msys2-devtools/runs/942546549?check_suite_focus=true

`pacman -Qkq` checks if all files that should be there are there and one was missing

I'm not sure how and why, and how likely. Let's watch out for similar cases..

### PR DESCRIPTION
**Pull request by lazka**
For some reason it sometimes loses files. It's not clear where the error
is, so let's disable for now.

Fixes #61

### CODE REVIEW

**Comment by lazka** [comment]
Alternatively we could check if all files are there at some point to pin down where the error happens.

**Comment by eine** [comment]
I think this PR is ok as a temporal solution. The logic is not removed, but just conditionally disabled.

Anyway, I believe it might be worth reporting this to GitHub. Maybe we can enhance our logic to track down when is it happening. But they might be able to detect it in their infrastructure too.

**Comment by lazka** [comment]
I can't really rule out that the problem isn't on our side, even though I don't know what it could be.

**Comment by eine** [comment]
Is the error consistent? I mean, is it fixed by restarting a job?

**Comment by lazka** [comment]
I haven't restarted the same job, but followup commits failed as well I think.

**Comment by lazka** [comment]
The above two jobs show it perfectly (ctrl+f the cache IDs in them). Either it didn't save the files properly, or didn't restore it properly, or any of our commands after the restore removed it (but in this case there was no update, so this should in theory be a noop)

**Pull request merged**
